# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalQC.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 709)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelFileList = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.labelFileList.setFont(font)
        self.labelFileList.setObjectName("labelFileList")
        self.verticalLayout.addWidget(self.labelFileList)
        self.tableWidgetFile = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidgetFile.setMinimumSize(QtCore.QSize(500, 0))
        self.tableWidgetFile.setObjectName("tableWidgetFile")
        self.tableWidgetFile.setColumnCount(0)
        self.tableWidgetFile.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidgetFile)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ButtonOpen = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonOpen.setObjectName("ButtonOpen")
        self.horizontalLayout.addWidget(self.ButtonOpen)
        self.ButtonClear = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonClear.setObjectName("ButtonClear")
        self.horizontalLayout.addWidget(self.ButtonClear)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelFileList_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.labelFileList_2.setFont(font)
        self.labelFileList_2.setObjectName("labelFileList_2")
        self.verticalLayout_2.addWidget(self.labelFileList_2)
        self.tableView = QtWidgets.QTableView(self.layoutWidget1)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ButtonConfirm = QtWidgets.QPushButton(self.layoutWidget1)
        self.ButtonConfirm.setObjectName("ButtonConfirm")
        self.horizontalLayout_2.addWidget(self.ButtonConfirm)
        self.ButtonExclude = QtWidgets.QPushButton(self.layoutWidget1)
        self.ButtonExclude.setObjectName("ButtonExclude")
        self.horizontalLayout_2.addWidget(self.ButtonExclude)
        self.ButtonShow = QtWidgets.QPushButton(self.layoutWidget1)
        self.ButtonShow.setObjectName("ButtonShow")
        self.horizontalLayout_2.addWidget(self.ButtonShow)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox1 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox1.setFont(font)
        self.groupBox1.setObjectName("groupBox1")
        self.groupBox2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox2.setFont(font)
        self.groupBox2.setObjectName("groupBox2")
        self.gridLayout.addWidget(self.splitter_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setObjectName("actionQuit")
        self.actionProteomics = QtWidgets.QAction(MainWindow)
        self.actionProteomics.setObjectName("actionProteomics")
        self.actionDatabase = QtWidgets.QAction(MainWindow)
        self.actionDatabase.setObjectName("actionDatabase")
        self.actionCETSA = QtWidgets.QAction(MainWindow)
        self.actionCETSA.setObjectName("actionCETSA")
        self.actionCalcPval = QtWidgets.QAction(MainWindow)
        self.actionCalcPval.setObjectName("actionCalcPval")
        self.actionTPP = QtWidgets.QAction(MainWindow)
        self.actionTPP.setObjectName("actionTPP")
        self.actionCheck_update = QtWidgets.QAction(MainWindow)
        self.actionCheck_update.setObjectName("actionCheck_update")
        self.actionCitation = QtWidgets.QAction(MainWindow)
        self.actionCitation.setObjectName("actionCitation")
        self.actionCheck_liences = QtWidgets.QAction(MainWindow)
        self.actionCheck_liences.setObjectName("actionCheck_liences")
        self.actionPreprocessing = QtWidgets.QAction(MainWindow)
        self.actionPreprocessing.setObjectName("actionPreprocessing")
        self.actionCalcComplex = QtWidgets.QAction(MainWindow)
        self.actionCalcComplex.setObjectName("actionCalcComplex")
        self.actioniTSA = QtWidgets.QAction(MainWindow)
        self.actioniTSA.setObjectName("actioniTSA")
        self.actionContact = QtWidgets.QAction(MainWindow)
        self.actionContact.setObjectName("actionContact")
        self.actionAnalDist = QtWidgets.QAction(MainWindow)
        self.actionAnalDist.setObjectName("actionAnalDist")
        self.actionExternal = QtWidgets.QAction(MainWindow)
        self.actionExternal.setObjectName("actionExternal")
        self.actionInflect = QtWidgets.QAction(MainWindow)
        self.actionInflect.setObjectName("actionInflect")
        self.actionNPARC = QtWidgets.QAction(MainWindow)
        self.actionNPARC.setObjectName("actionNPARC")
        self.actionINFLECT = QtWidgets.QAction(MainWindow)
        self.actionINFLECT.setObjectName("actionINFLECT")
        self.actionDistance = QtWidgets.QAction(MainWindow)
        self.actionDistance.setObjectName("actionDistance")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelFileList.setText(_translate("MainWindow", "File List"))
        self.ButtonOpen.setText(_translate("MainWindow", "Open"))
        self.ButtonClear.setText(_translate("MainWindow", "Clear"))
        self.labelFileList_2.setText(_translate("MainWindow", "Protein Table"))
        self.ButtonConfirm.setText(_translate("MainWindow", "With Missing"))
        self.ButtonExclude.setText(_translate("MainWindow", "Exclude Missing"))
        self.ButtonShow.setText(_translate("MainWindow", "Show"))
        self.groupBox1.setTitle(_translate("MainWindow", "RSD Distribution"))
        self.groupBox2.setTitle(_translate("MainWindow", "Box Plot"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save..."))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionProteomics.setText(_translate("MainWindow", "Load proteomics..."))
        self.actionDatabase.setText(_translate("MainWindow", "Load PPI database..."))
        self.actionCETSA.setText(_translate("MainWindow", "Thermal shift analysis ..."))
        self.actionCalcPval.setText(_translate("MainWindow", "Calculate p-values of protein complex ..."))
        self.actionTPP.setText(_translate("MainWindow", "Run TPP Method"))
        self.actionCheck_update.setText(_translate("MainWindow", "Check update ..."))
        self.actionCitation.setText(_translate("MainWindow", "Check citation ..."))
        self.actionCheck_liences.setText(_translate("MainWindow", "Check licence..."))
        self.actionPreprocessing.setText(_translate("MainWindow", "Preprocessing..."))
        self.actionCalcComplex.setText(_translate("MainWindow", "Protein complex analysis..."))
        self.actioniTSA.setText(_translate("MainWindow", "Isothermal shift analysis..."))
        self.actionContact.setText(_translate("MainWindow", "Contact author..."))
        self.actionAnalDist.setText(_translate("MainWindow", "Distance-based analysis..."))
        self.actionExternal.setText(_translate("MainWindow", "External tool analysis..."))
        self.actionInflect.setText(_translate("MainWindow", "Inflect analysis..."))
        self.actionNPARC.setText(_translate("MainWindow", "Run NPARC Method"))
        self.actionINFLECT.setText(_translate("MainWindow", "Run Inflect Method"))
        self.actionDistance.setText(_translate("MainWindow", "Run Distance Mehod"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

