# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnaliTSA.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1186, 1081)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.verticalLayout_12.addWidget(self.label_1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.comboBoxMethod = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxMethod.setObjectName("comboBoxMethod")
        self.horizontalLayout_5.addWidget(self.comboBoxMethod)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.doubleSpinBoxFCthres = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxFCthres.setProperty("value", 2.0)
        self.doubleSpinBoxFCthres.setObjectName("doubleSpinBoxFCthres")
        self.horizontalLayout_6.addWidget(self.doubleSpinBoxFCthres)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.doubleSpinBoxPthres = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxPthres.setProperty("value", 2.0)
        self.doubleSpinBoxPthres.setObjectName("doubleSpinBoxPthres")
        self.horizontalLayout_7.addWidget(self.doubleSpinBoxPthres)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.verticalLayout_14.addLayout(self.verticalLayout_12)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButtonData = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonData.setObjectName("pushButtonData")
        self.horizontalLayout_8.addWidget(self.pushButtonData)
        self.pushButtonOK = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout_8.addWidget(self.pushButtonOK)
        self.pushButtonClose = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.horizontalLayout_8.addWidget(self.pushButtonClose)
        self.verticalLayout_14.addLayout(self.horizontalLayout_8)
        self.verticalLayout_16.addLayout(self.verticalLayout_14)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_16.addWidget(self.label_8)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tableWidgetLabel = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidgetLabel.setMinimumSize(QtCore.QSize(400, 0))
        self.tableWidgetLabel.setObjectName("tableWidgetLabel")
        self.tableWidgetLabel.setColumnCount(0)
        self.tableWidgetLabel.setRowCount(0)
        self.verticalLayout_15.addWidget(self.tableWidgetLabel)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.pushButtonSave = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_9.addWidget(self.pushButtonSave)
        self.verticalLayout_15.addLayout(self.horizontalLayout_9)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_13.addWidget(self.label_11)
        self.tableViewData = QtWidgets.QTableView(self.layoutWidget1)
        self.tableViewData.setMinimumSize(QtCore.QSize(0, 250))
        self.tableViewData.setObjectName("tableViewData")
        self.verticalLayout_13.addWidget(self.tableViewData)
        self.groupBoxVolcano = QtWidgets.QGroupBox(self.splitter)
        self.groupBoxVolcano.setMinimumSize(QtCore.QSize(0, 250))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.groupBoxVolcano.setFont(font)
        self.groupBoxVolcano.setObjectName("groupBoxVolcano")
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_1.setText(_translate("Form", "Parameters for iTSA analysis:"))
        self.label_2.setText(_translate("Form", "Select methods"))
        self.label_9.setText(_translate("Form", "Fold change threshold"))
        self.label_10.setText(_translate("Form", "P-value threshold"))
        self.pushButtonData.setText(_translate("Form", "Data"))
        self.pushButtonOK.setText(_translate("Form", "Confirm"))
        self.pushButtonClose.setText(_translate("Form", "Cancel"))
        self.label_8.setText(_translate("Form", "Label setting"))
        self.pushButtonSave.setText(_translate("Form", "Save"))
        self.label_11.setText(_translate("Form", "Data viewer"))
        self.groupBoxVolcano.setTitle(_translate("Form", "Volcano plot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
