# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalExter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1082, 784)
        Form.setMinimumSize(QtCore.QSize(1082, 784))
        Form.setMaximumSize(QtCore.QSize(1082, 784))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.textBrowserSource = QtWidgets.QTextBrowser(Form)
        self.textBrowserSource.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserSource.setObjectName("textBrowserSource")
        self.verticalLayout.addWidget(self.textBrowserSource)
        self.label_8 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.textBrowserParams = QtWidgets.QTextBrowser(Form)
        self.textBrowserParams.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserParams.setObjectName("textBrowserParams")
        self.verticalLayout.addWidget(self.textBrowserParams)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ButtonSource = QtWidgets.QPushButton(Form)
        self.ButtonSource.setObjectName("ButtonSource")
        self.horizontalLayout.addWidget(self.ButtonSource)
        self.ButtonParams = QtWidgets.QPushButton(Form)
        self.ButtonParams.setObjectName("ButtonParams")
        self.horizontalLayout.addWidget(self.ButtonParams)
        self.ButtonConfirm = QtWidgets.QPushButton(Form)
        self.ButtonConfirm.setObjectName("ButtonConfirm")
        self.horizontalLayout.addWidget(self.ButtonConfirm)
        self.ButtonCancel = QtWidgets.QPushButton(Form)
        self.ButtonCancel.setObjectName("ButtonCancel")
        self.horizontalLayout.addWidget(self.ButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.tableWidgetProteinList = QtWidgets.QTableWidget(Form)
        self.tableWidgetProteinList.setMinimumSize(QtCore.QSize(0, 500))
        self.tableWidgetProteinList.setObjectName("tableWidgetProteinList")
        self.tableWidgetProteinList.setColumnCount(0)
        self.tableWidgetProteinList.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidgetProteinList)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ButtonShow = QtWidgets.QPushButton(Form)
        self.ButtonShow.setObjectName("ButtonShow")
        self.horizontalLayout_2.addWidget(self.ButtonShow)
        self.pushButtonSave = QtWidgets.QPushButton(Form)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_2.addWidget(self.pushButtonSave)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxAvg = QtWidgets.QGroupBox(Form)
        self.groupBoxAvg.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.groupBoxAvg.setFont(font)
        self.groupBoxAvg.setObjectName("groupBoxAvg")
        self.verticalLayout_2.addWidget(self.groupBoxAvg)
        self.groupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Distance-based TPP analysis:"))
        self.label_7.setText(_translate("Form", "Method Selection"))
        self.label_6.setText(_translate("Form", "Source Path"))
        self.label_8.setText(_translate("Form", "Parameter Path"))
        self.ButtonSource.setText(_translate("Form", "Source"))
        self.ButtonParams.setText(_translate("Form", "Params"))
        self.ButtonConfirm.setText(_translate("Form", "Confirm"))
        self.ButtonCancel.setText(_translate("Form", "Cancel"))
        self.label.setText(_translate("Form", "Protein list sorted by scores:"))
        self.ButtonShow.setText(_translate("Form", "Show Curve"))
        self.pushButtonSave.setText(_translate("Form", "Save Result"))
        self.groupBoxAvg.setTitle(_translate("Form", "Average thermal shift curves:"))
        self.groupBox.setTitle(_translate("Form", "Thermal shift curves comparison:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

