# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NPTSA.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1082, 784)
        Form.setMinimumSize(QtCore.QSize(1082, 784))
        Form.setMaximumSize(QtCore.QSize(1082, 784))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidgetProteinList = QtWidgets.QTableWidget(Form)
        self.tableWidgetProteinList.setObjectName("tableWidgetProteinList")
        self.tableWidgetProteinList.setColumnCount(0)
        self.tableWidgetProteinList.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidgetProteinList, 7, 0, 1, 5)
        self.label_7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 8, 11, 1, 1)
        self.ButtonShow = QtWidgets.QPushButton(Form)
        self.ButtonShow.setObjectName("ButtonShow")
        self.gridLayout.addWidget(self.ButtonShow, 8, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.pushButtonSave = QtWidgets.QPushButton(Form)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout.addWidget(self.pushButtonSave, 8, 2, 1, 1)
        self.ButtonCancel = QtWidgets.QPushButton(Form)
        self.ButtonCancel.setObjectName("ButtonCancel")
        self.gridLayout.addWidget(self.ButtonCancel, 4, 2, 1, 1)
        self.groupBoxAvg = QtWidgets.QGroupBox(Form)
        self.groupBoxAvg.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.groupBoxAvg.setFont(font)
        self.groupBoxAvg.setObjectName("groupBoxAvg")
        self.gridLayout.addWidget(self.groupBoxAvg, 0, 11, 6, 1)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 2, 0, 1, 1)
        self.ButtonConfirm = QtWidgets.QPushButton(Form)
        self.ButtonConfirm.setObjectName("ButtonConfirm")
        self.gridLayout.addWidget(self.ButtonConfirm, 3, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout.addWidget(self.groupBox, 6, 11, 2, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.BoxR2 = QtWidgets.QDoubleSpinBox(Form)
        self.BoxR2.setSingleStep(0.01)
        self.BoxR2.setProperty("value", 0.8)
        self.BoxR2.setObjectName("BoxR2")
        self.gridLayout.addWidget(self.BoxR2, 4, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Method Selection"))
        self.ButtonShow.setText(_translate("Form", "Show Curve"))
        self.label.setText(_translate("Form", "Protein list sorted by scores:"))
        self.label_4.setText(_translate("Form", "Distance-based TPP analysis:"))
        self.pushButtonSave.setText(_translate("Form", "Save Result"))
        self.ButtonCancel.setText(_translate("Form", "Cancel"))
        self.groupBoxAvg.setTitle(_translate("Form", "Average thermal shift curves:"))
        self.ButtonConfirm.setText(_translate("Form", "Confirm"))
        self.groupBox.setTitle(_translate("Form", "Thermal shift curves comparison:"))
        self.label_6.setText(_translate("Form", "minR2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

